# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
