# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0002_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='about_me/')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
    ]
