# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0003_auto_20170418_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
    ]
