# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=600)),
            ],
        ),
    ]
