# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0005_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto_autor', models.ImageField(upload_to='', verbose_name='comentarios/')),
            ],
        ),
    ]
