# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio_app', '0010_auto_20170419_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='mi_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proy_cat', to='portafolio_app.categorias'),
        ),
    ]
